services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2
    restart: unless-stopped
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ../../data/npm:/data
      - ../../data/letsencrypt:/etc/letsencrypt
    ports: ["80:80", "443:443"]
