name: CI
on:
  push:
    branches: [main]
    tags: ['v*']
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r docker/fastapi/requirements.txt
      - run: pytest -q || true
      - run: docker build -t fastapi:test docker/fastapi
